---
title: "Contributing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CI/CD Information}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The page describes the general plan for ensuring that the main branch does not break. Currently, the repository is in a very early development stage, so breaking changes will not matter too much, but over time more tests and checks will be added to keep everything working.

**This repository is in a very early stage, so things may change substantially here. Please get in touch if you would like to contribute, or have any suggestions regarding anything.**

## Issues

If you have any issues with using the package, please log them on the GitHub [https://github.com/jrs0/icdb/issues](Issues Page). **You are currently extremely likely to have issues: the vast majority of the package is very underdeveloped and mostly untested**. However, if you feel brave enough to try to use it, we would greatly value your feedback/suggestions.

## The main branch

The idea is that the main branch always works. The branch is protected, meaning it is not possible to directly push to it. Instead, you must create a pull request, meeting the requirements below:

* The R CMD Check must pass (devtools::check())
* Tests pass, and test coverage must exceed 60% (this number will increase with time)
* The documentation must build successfully

## How to get code into main

Follow the steps below to make changes to the repository:

* Create a new branch, from an up to date copy of main (or pull the current state of main into a pre-existing branch, if you already have it). By making sure your branch is as up to date as possible with main, you will make the subsequent pull request easier (as your new branch will be similar to main)
* Make changes to your local branch
* Run `devtools::check()` and `devtools::build_site()` to ensure that the code passes the checks and the documentation works. If these fail, the pull request will not succeed.
* When you have finished making changes, open a pull request on GitHub. Once the automatic checks have passed, you should be able to merge the changes into main.
* Note that if you spend quite a while on your branch, consider periodically pulling main into your branch and performing any required merges, so that your branch remains close to main.

