// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// new_icd10_impl
Rcpp::List new_icd10_impl(const Rcpp::CharacterVector& str, const std::string& codes_file);
RcppExport SEXP _icdb_new_icd10_impl(SEXP strSEXP, SEXP codes_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type str(strSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type codes_file(codes_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(new_icd10_impl(str, codes_file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_icdb_new_icd10_impl", (DL_FUNC) &_icdb_new_icd10_impl, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_icdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
