##'
##' 
NULL

##' Read the BNSSG system-wide dataset guide document into a mapping file.
##'
##' This function expects to find a sheet called "Data Tables and Fields",
##' containing a table of column names in the tables with documentation.
##' The table should have four columns: `Table Name`, `Column Name`,
##' `Data Type` and `Description`.
##' 
##' @title Read SWD guide
##' @param spec The SWD guide document (.xlsx)
##' @param sheet The name of the sheet to read
##' @param output The file path to write the output
##' 
gen_swd_map <- function(spec, sheet, output = filename)
{
    sheet <- "Data Tables and Fields"
    
    ## Read the excel sheet into a variable 
    xx <- readxl::read_xlsx(spec, sheet, skip = 3)
    
    tables <- xx$`Table Name` %>%
        unique()

    tt <- list()
    for (tab in tables)
    {
        ## Get the source columns
        cc <- xx %>%
            dplyr::filter(`Table Name` == tab) %>%
            dplyr::select(`Column Name`, `Description`) %>%
            purrr::pmap(~ list(
                            column = .x,
                            docs = .y,
                            source = c(.x),
                            strategy = "coalesce"
                        ))
        
        tt <- c(tt, list(list(
                        table = tab,
                        source = "WRITE_ME",
                        docs = "WRITE ME",
                        columns = cc
                    )
                    )
                )
    }

    ## Write the output file
    filename <- paste0(janitor::make_clean_names(sheet), ".yaml")
    yaml::write_yaml(tt, file = output)
}

##' This function parses the technical output specification for a
##' CDS dataset into a mapping.yaml file suitable for use
##' in mapped_server.
##'
##' The technical output specification (TOS) is a document that
##' lists information about databases, such as column names and
##' documentation. Pass this file (and excel document) to this
##' function, along with the name of the sheet containing the
##' specification you want to parse.
##'
##' In the generated output file, you will need to specify the
##' source database and tables names in order to map the file
##' to a particular database.
##' 
##' @title Parse CDS technical output specification
##' @param tos The path to the technical output specification file
##' @param sheet The sheet name (corresponding to a database) to use
##' @param output The path to an output file for the generated mapping.yaml
##' This parameter is optional. If it is not specified, it will be
##' generated automatically based on the sheet name.
##' 
##' @export
gen_cds_map <- function(tos, sheet, output = filename)
{
    ## Read the excel sheet into a variable 
    xx <- readxl::read_xlsx(tos, sheet)

    ## Extract only the rows that begin with a valid
    ## UID (the code beginning with CDS)
    xx <- xx %>% dplyr::filter(grepl("^CDS", .[[1]]))

    ## Drop all columns except the xml schema name
    ## and the documentation column
    xx <- xx %>%
        dplyr::rename(source_column = ...3, docs = ...4) %>%
        dplyr::select(source_column, docs)

    ## The next line removes the merged cells (the ones
    ## containing "-/-". The validity of this makes the
    ## assumption that the documentation is all contained
    ## in the same row as the identifier name, and not
    ## split over multiple rows downwards (to check).
    xx <- xx %>% dplyr::filter(!grepl("-/-", source_column))

    ## Generate logical column names from the source
    ## column names
    xx <- xx %>% dplyr::mutate(column = janitor::make_clean_names(source_column))
    
    ## At this point, there is enough minimal information
    ## to create the mapping file. Create the columns
    ## structure in the right format for the mapping
    fn <- function(source_column, docs, column)
    {
        xx <- list(
            docs = docs,
            use = FALSE,
            source_columns = list(),
            strategy = "coalesce"
        )
        xx$source_columns[[source_column]] = "Generated by parsing TOS"
        xx
    }
    cc <- xx %>% purrr::pmap(fn)
    names(cc) <- xx$column
    
    ## Create the mapping file structure
    mapping <- list(
        databases = list(
            dbname = list(
                docs = "WRITE ME",
                source_database = "WRITE ME",
                tables = list(
                    tabname = list(
                        docs = "WRITE ME",
                        source_table = "WRITE ME",
                        columns = cc
                    )
                )
            )
        ))

    
    ## Write the output file
    filename <- paste0(janitor::make_clean_names(sheet), ".yaml")
    yaml::write_yaml(mapping, file = output)
}
