# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' \brief Comparison of category with raw code
#'
#' This function is the main comparison operator that is
#' used in the binary search to find a raw code in the ICD-10
#' codes file. The comparison is intended for use with
#' lower_bound, where categories from a vector are compared
#' with a fixed str to find the first category that does not
#' satisfy cat < str (i.e. the lowest cat such that cat >= str).
#' The meaning is clearer by thinking in terms of str > cat, which
#' means that str is larger (lexicographically) than the upper
#' element of the index of cat.
#'
#'
NULL

#' Parse a single ICD-10 string into a vector of indices that locates
#' it in the code definition structure, and handle parsing errors. This
#' function is the counterpart to the R function icd10_str_to_indices.
#'
#' The returned object is a list containing the following fields:
#' - type: a integer describing the result of the parse. 0 for
#'   success; 1 for empty string; 2 for invalid code.
#' - indices: if success, a vector of indices locating
#' - trailing: an content at the end of the string that was not
#'   parsed (sometimes ICD-10 codes contain trailing matter -- the
#'   goal is to eventually interpret all of this)
#' - groups: a character vector of groups that contain this code
#'
#' This function is the faster implementation of the ICD-10 parser.
#' The input is a vector of strings to be parsed, and the output is
#' a list of three vectors (the same length as the input) containing
#' information about the parsed codes.
#'
#' Note: passing groups by value is deliberate, because it is
#' modified and should not modify the caller's version. Todo:
#' try to remove this, it might be possible to keep only one
#' copy and modify it globally.
#' 
#' @param str The input character vector of strings that should be
#' parsed. The strings can have leading and trailing whitespace,
#' which will be removed before parsing by this function.
#' @param code_def The code definition structure, which is a nested
#' list of lists following the structure of the icd10.yaml file.
#' @return A named list containing indices, type and groups
#' 
#' 
NULL

#' Implementation of the ICD-10 parser for vectors of ICD-10 strings
#'
#' This function is the faster implementation of the ICD-10 parser.
#' The input is a vector of strings to be parsed, and the output is
#' a list of three vectors (the same length as the input) containing
#' information about the parsed codes.
#' 
#' @param str The input character vector of strings that should be
#' parsed. The strings can have leading and trailing whitespace,
#' which will be removed before parsing by this function.
#' @param code_def The code definition structure, which is a nested
#' list of lists following the structure of the icd10.yaml file.
#' @return A named list containing indices, type and groups
#' 
#' 
new_icd10_impl <- function(str, code_def) {
    .Call(`_icdb_new_icd10_impl`, str, code_def)
}

