# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_icd10_impl <- function(str, codes_file) {
    .Call(`_icdb_new_icd10_impl`, str, codes_file)
}

