# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementation of the ICD-10 parser for vectors of ICD-10 strings
#'
#' This function is the faster implementation of the ICD-10 parser.
#' The input is a vector of strings to be parsed, and the output is
#' a list of three vectors (the same length as the input) containing
#' information about the parsed codes.
#' 
#' @param str The input character vector of strings that should be
#' parsed
#' @param codes_file The path to a codes definition file containing
#' the ICD-10 codes and groups
#' @return A named list containing indices, type and groups
#' 
new_icd10_impl <- function(str, codes_file) {
    .Call(`_icdb_new_icd10_impl`, str, codes_file)
}

